export default {
  CHANGE_CITY: `CHANGE_CITY`,
  LOAD_OFFERS: `LOAD_OFFERS`,
  AUTHORIZE: `AUTHORIZE`,
  LOAD_FAVORITES: `LOAD_FAVORITES`,
  TOGGLE_FAVORITE_HOTEL: `TOGGLE_FAVORITE_HOTEL`,
  CHANGE_ACTIVE_OFFER: `CHANGE_ACTIVE_OFFER`,
  SET_CURRENT_OFFER_ID_DETAIL: `SET_CURRENT_OFFER_ID_DETAIL`,
  LOAD_COMMENTS_FOR_OFFER: `LOAD_COMMENTS_FOR_OFFER`
};
